---

- name: Install lighttpd package on Ubuntu Linux servers
  hosts: web_srv
  become: true
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Update repositories and install lighttpd package
      ansible.builtin.apt:
        name: lighttpd
        update_cache: true
        state: present

    - name: Copy local index.html file to web servers
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'
