- name: Hello World
  hosts: localhost
  gather_facts: no

  vars:
    test:
    - test1
    - test2
    - test3

  vars_files:
    - "vars/cloned_vms.yaml"

  tasks:
    - name: Loop demo
      debug:
        msg:
        - "{{ test }}"
        - "{{ cloned_vms }}"