---

- name: ansible.builtin.copy module
  hosts: web_srv
  gather_facts: no

  tasks:
    - name: copy file
      ansible.builtin.copy:
        src: demo.conf
        dest: /home/student/demo.conf
        owner: student
        group: student
        mode: '0644'